### PR TITLE
edit file structure & fix uninstall script and delete binary

### PR DESCRIPTION
**Pull request by yucellmustafa**
Fixed the problem in uninstall.sh. It would be convenient to keep the binary files in the releases instead of the project folder.
(bad my english, sorry)

### CODE REVIEW

**Comment by hamza-Algohary** [comment]
Hello Mustafa.
I've already deleted the install.sh and unistall.sh because they are supposed to be inside the tarball package. So remove the third commit and I'll merge your request.
Thanks

**Comment by yucellmustafa** [comment]
actually i changed the tarrball as well. There was a problem with the uninstall script. and one script is enough instead of two scripts. You can browse the tarball via v1.3 in my repo. OK, I'll take care of the rest.

**Comment by yucellmustafa** [comment]
I changed the file structure in the last commit, actually it should stop. because in the main folder of the repo there should be codes. It is more organized to have the screenshots in a separate folder.

**Review by hamza-Algohary — APPROVED** [review]

**Comment by hamza-Algohary** [comment]
I'll have to close this pull request because I'm not able to fully review your changes

**Pull request closed without merging**
